### ISSUE TITLE
should we let user use display as a string variabe ?

### ISSUE THREAD

**Issue by SuperQuentin** [HEIGVD-PRG1-F-2022/prg1f-io#13]
Des la conception on est parti du principe que l'utilisateur dois formater les différents éléments a afficher sous la forme de string.

Pour l'instant il manque une fonction du style appendContent() qui permettrais d'ajouter du contenu en plus et non de le remplacer uniquement.

Dans l'optique d'améliorer l'utilisation de la librairie je trouve qu'il serait intéressant de pouvoir modifier le contenu directement à l'aide des opérateurs ´=´ et ´+=´ qui ferait respectivement un setContent et un appendContent.

ça serait surtout utile dans le cadre ou il y aurait des constructions complexe par exemple si quelqu'un aimerais refaire ça propre grille pour éviter l'utilisation de variable temporaire.

Exemple : 
```c++
// Before
Display display();
string tmp;

vector<vector<string>> grid(6, vector<string>(6, "0"));
  for (auto &row : grid) {
    for (auto &item : row) {
       tpm += item;
    }
    tpm += "\n";
  }
  display.show(tmp);

// After

Display display();

vector<vector<string>> grid(6, vector<string>(6, "0"));
  for (auto &row : grid) {
    for (auto &item : row) {
       display += item;
    }
    display += "\n";
  }
  display.show(); // or cout << display

```

**Comment by ineiti** [comment]
Please change this issue:
- give a short title for it
- explain in more details in the description

Do you want to overload the + operator in the `Display` class? That does not make a lot of sense... Perhaps an `addContent` would be more appropriate.
