### ISSUE TITLE
Add a custom flush function

### ISSUE THREAD

**Issue by SuperQuentin** [HEIGVD-PRG1-F-2022/prg1f-io#25]
It will be helpful when we need to display the content one time and reset content to an empty string

**Comment by ineiti** [comment]
Isn't this the purpose of the `show` method?

**Comment by SuperQuentin** [comment]
That was i question i ask myself if show() should flush output but, i think it will be confusing if the default behavior is to flush the content

**Comment by ineiti** [comment]
As it inherits from `string`, you can use `clear()`.
