### ISSUE TITLE
Code message when switch console to utf-8(Window Only)

### ISSUE THREAD

**Issue by SuperQuentin** [HEIGVD-PRG1-F-2022/prg1f-io#7]
![image](https://user-images.githubusercontent.com/36150436/203566462-305b4d91-ca45-4ac0-9b68-d6d53fd2aa27.png)

**Comment by ineiti** [comment]
Est-ce qu'on peut enlever ceci? Ou faut-il vivre avec? Faire un `cls` après?

**Comment by A2va** [comment]
Peut-être en utilisant la fonction `SetConsoleOutputCP` de `windows.h` au lieu de `system`
https://stackoverflow.com/questions/1371012/how-do-i-print-utf-8-from-c-console-application-on-windows

**Comment by ineiti** [comment]
Est-ce quelqu'un avec un windows peut essayer, svp?
